version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ci_debugger_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ci_debugger
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ci_debugger_pgdata:/var/lib/postgresql/data

volumes:
  ci_debugger_pgdata: